#!/usr/bin/env python3
"""Pack assets/{tiles,walls,items,npcs,buffs,sfx} into src/assets_data.js as data URIs
so the game runs straight from file:// without canvas-taint or fetch restrictions."""
import os, base64, json
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out={}
for folder in ['tiles','walls','items','npcs','buffs','hair','sfx']:
    d=os.path.join(ROOT,'assets',folder)
    for fn in sorted(os.listdir(d)):
        p=os.path.join(d,fn)
        mime='image/png' if fn.endswith('.png') else 'audio/wav'
        key=folder+'/'+os.path.splitext(fn)[0]
        out[key]='data:%s;base64,%s'%(mime,base64.b64encode(open(p,'rb').read()).decode())
with open(os.path.join(ROOT,'src','assets_data.js'),'w') as f:
    f.write('// generated by tools/build_assets.py — do not edit\nconst ASSET_DATA=')
    json.dump(out,f,separators=(',',':'))
    f.write(';\n')
print(len(out),'assets packed')
