// ---------- all the brainrot text lives here ----------
const MEME = {
  titles: [
    'Terrari67: Dig Peon, Dig! (Six Seven)',
    'Terrari67: Skibidi Dig Dig Yes Yes',
    'Terrari67: Also Try Ohio',
    'Terrari67: Now With 67% More Aura',
    'Terrari67: The Grindset Never Stops',
    'Terrari67: Touch Grass, Then Mine It',
    'Terrari67: Fanum Taxed Edition',
    'Terrari67: Tung Tung Tung Sahur',
    'Terrari67: No Cap, All Blocks',
    'Terrari67: Rizz of the Worlds',
    'Terrari67: Mewing Is Mandatory',
    'Terrari67: Bombardiro Crocodilo Approved',
    'Terrari67: Chat, Is This Real?',
    'Terrari67: Its Giving Sandbox',
    'Terrari67: Lock In',
    'Terrari67: Certified Brainrot',
    'Terrari67: Delulu Is The Solulu',
    'Terrari67: Tralalero Tralala',
    'Terrari67: Sigma Male Grindset Simulator',
    'Terrari67: 6️⃣7️⃣',
  ],
  splashes: [
    'SIX SEVEN!', 'Dictionary.com word of the year!', 'Skibidi approved!', 'Now in Ohio!', '+1000 aura',
    'No cap fr fr', 'Mewing streak: 67 days', 'Fanum tax not included', 'Italian brainrot inside!',
    "It's giving Terraria", 'Chat is this real?', 'Rage bait (tm)', 'Lock in.', 'W game', 'Gyatt!',
    'Unc approved', 'Delulu edition', 'Big back energy', 'Aura farming simulator', 'Crash out responsibly',
  ],
  worldgen: [
    'Generating terrain (no cap)', 'Adding sand (it is giving beach)', 'Putting dirt behind dirt (for the plot)',
    'Placing rocks in the dirt (lowkey)', 'Carving tunnels (fr fr)', 'Rizzing up the caves', 'Placing Copium',
    'Sprinkling Ironic ore', 'Grinding Sigma ore', 'Hiding Rizzium', 'Building Ohio', 'Fanum taxing the underworld',
    'Pouring water (hydrate or diedrate)', 'Pouring lava (it is lava, bro)', 'Spreading brainrot', 'Planting trees (touch grass)',
    'Growing cacti', 'Placing Aura Crystals', 'Hiding chests (sus)', 'Breaking pots in advance (jk)',
    'Summoning the Brainrot Altars', 'Adding sixes and sevens', 'Skibidifying the toilets', 'Mewing the mountains',
    'Locking in', 'Settling liquids (touching grass)', 'Final touches (ate and left no crumbs)',
  ],
  deaths: {
    generic: ['{p} got cooked.', '{p} fell off.', '{p} was mogged.', '{p} lost all their aura.', '{p} is no longer him.', "{p}'s aura dropped to zero.", '{p} crashed out.', '{p} took an L.'],
    fall: ['{p} fell off (literally).', '{p} forgot to lock in mid-air.', "{p} didn't have the Lucky Horseshoe. Skill issue.", '{p} found out gravity is sigma.'],
    lava: ['{p} tried to swim in Ohio.', '{p} got fried. Only in Ohio.', '{p} learned that lava is, in fact, hot.', '{p} melted. Chat, is this real?'],
    drown: ['{p} forgot to breathe.', '{p} is sleeping with Tralalero.', '{p} drowned in toilet water.'],
    enemy: ['{p} was cooked by {e}.', '{p} got mogged by {e}.', '{e} fanum taxed {p}\'s life.', '{p} was ratio\'d by {e}.', '{e} made {p} crash out.', '{p} got skibidi\'d by {e}.', '{e} ate and left no crumbs of {p}.'],
  },
  deathScreen: ['You got cooked.', 'You fell off.', 'Skill issue.', 'L + ratio.', 'You lost all your aura.', 'Bro got mogged.'],
  respawnTips: [
    'Tip: Press 6 and 7 together. Trust.', 'Tip: The Rizzler knows things. Talk to him.', 'Tip: Aura Crystals increase your max life.',
    'Tip: Build a house. NPCs need a place to crash out.', 'Tip: Tung Tung Tung Sahur wakes up at 3 AM.', 'Tip: Side-Eyes drop lenses. Six lenses = one bad decision.',
    'Tip: The Rizzler Voodoo Doll + lava = final boss. Allegedly.', 'Tip: Unc sells stuff. Fanum tax included.', 'Tip: Mine Ohiostone with a Brainrot Pickaxe.',
    'Tip: Water + lava = obsidian. Science is lowkey bussin.', 'Tip: Hold Shift to see the smart cursor. (It is not smart.)',
  ],
  // town npc dialogue
  npc: {
    guide: {
      name: 'The Rizzler', title: 'The Rizzler (Guide)', names: ['Kai', 'Duke', 'Rizzington', 'Brody', 'Jaxon', 'Brayden', 'Tyler'],
      lines: [
        "Greetings, {p}. Is there something I can help you with? Other than your rizz. That is beyond saving.",
        "You can use your pickaxe to dig through dirt, and your axe to chop down trees. Touch grass, then chop it.",
        "If you get stuck, press Escape to open your inventory. It's giving organization.",
        "Build a house with a door, a chair, a table and a light. NPCs have standards, bro.",
        "Six lenses at a Brainrot Altar makes a Suspicious Side-Eye. Use it at night if you're brave. Or delulu.",
        "Night brings the Skibidi Toilets. Dop dop dop yes yes. Stay inside.",
        "I heard there's a place called Ohio way down below. Only the sigmas return.",
        "Ohiostone needs a Brainrot Pickaxe. Brainrot Ore drops from the Eye of Ohio. It all connects. Lock in.",
        "Whatever you do, do NOT throw a Rizzler Voodoo Doll into lava. Please. I'm begging. For my aura.",
        "Six seven? Six seven. SIX SEVEN! ...Sorry. It's a condition.",
        "Your aura is looking kinda mid today. Go farm some.",
        "Life Crystals — I mean Aura Crystals — are pink and glowing, hidden in caves. Smash 'em with a pickaxe.",
      ],
    },
    merchant: {
      name: 'Unc', title: 'Unc (Merchant)', names: ['Unc Bob', 'Unc Larry', 'Unc Gerald', 'Unc Frank', 'Unc Walter'],
      lines: [
        "Back in my day we didn't have 'rizz', we had charisma. Buy something.",
        "Unc still got it. Unc's prices, however, include a 6.7% Fanum tax.",
        "You kids and your six-seven. Anyway, torches are 50 copper.",
        "I've been selling torches since before skibidi was a toilet.",
        "Unc status achieved. Unc wares available.",
        "Dubai chocolate? Yeah I got some. Don't ask where I got it.",
      ],
      arrive: 'Unc has arrived! (He is not your actual uncle.)',
    },
    nurse: {
      name: 'Nurse Glaze', title: 'Nurse Glaze (Nurse)', names: ['Nurse Kayla', 'Nurse Brielle', 'Nurse Aubrey', 'Nurse Sloane'],
      lines: [
        "You look cooked. Let me glaze you back to full health — for a fee.",
        "I'm not glazing, you really are the most injured person I've seen today.",
        "Please stop getting fanum taxed by slimes. It is embarrassing for both of us.",
        "Healing costs aura. That's just the economy, bestie.",
      ],
      arrive: 'Nurse Glaze has arrived!',
    },
    demolitionist: {
      name: 'Bombardiro Jr.', title: 'Bombardiro Jr. (Demolitionist)', names: ['Bombardino', 'Crocodilo Jr.', 'Bombastico'],
      lines: [
        "BOMBARDIRO CROCODILO! ...That was my dad. I just sell the bombs.",
        "Explosives are the fastest way to dig. Also the fastest way to crash out.",
        "Crocodilo Dynamite. Handle with italian care.",
      ],
      arrive: 'Bombardiro Jr. has arrived! Take cover!',
    },
    arms_dealer: {
      name: 'Sigma Dealer', title: 'Sigma Dealer (Arms Dealer)', names: ['Patrick B.', 'Thomas S.', 'Sigma Steve'],
      lines: [
        "A true sigma never misses. Buy bullets anyway.",
        "Minishark. Tralalero Jr. Half shark, half gun. No further questions.",
        "Grindset rule #67: always carry ammo.",
      ],
      arrive: 'The Sigma Dealer has arrived! (Grindset intensifies.)',
    },
    dryad: {
      name: 'Delulu Dryad', title: 'Delulu Dryad (Dryad)', names: ['Luna', 'Willow', 'Solulu', 'Delilah'],
      lines: [
        "The brainrot is spreading. I can feel it. My mind is... skibidi...",
        "Delulu is the solulu. Also, buy a Labubu.",
        "You have defeated great foes. The world's vibes are shifting.",
        "Touch grass, {p}. Literally. I sell the seeds.",
      ],
      arrive: 'The Delulu Dryad has arrived!',
    },
  },
  achievements: {
    timber: ['Timber!!', 'Chop down your first tree. Touch grass (lethally).'],
    benched: ['Benched', 'Craft a Work Bench. Grindset: activated.'],
    ooo_shiny: ['Ooo! Shiny!', 'Mine your first ore.'],
    heart_breaker: ['Aura Farmer', 'Smash your first Aura Crystal.'],
    six_seven: ['SIX SEVEN', 'Hit an enemy for exactly 67 damage. 🤲'],
    six_seven_emote: ['Brainrot Certified', 'Perform the 6-7.'],
    slayer: ['Skibidi Slayer', 'Defeat a Skibidi Toilet.'],
    king_slime: ['Slime King? More like Slime Mid', 'Defeat King Skibidi.'],
    eye_of_cthulhu: ['Side-Eye Mogged', 'Defeat the Eye of Ohio.'],
    tung_sahur: ['Sahur Survivor', 'Defeat Tung Tung Tung Sahur.'],
    wall_of_flesh: ['Hard Mogged', 'Defeat the Wall of Brainrot. You are him.'],
    ohio: ['Only In Ohio', 'Reach Ohio (the Underworld).'],
    fanum: ['Fanum Taxed', 'Get robbed by Fanum.'],
    rich: ['Aura Maxxing', 'Hold 1 gold aura at once.'],
    home: ['No Place Like Home', 'Have a town NPC move into a house.'],
    cooked: ['Cooked', 'Die for the first time. It happens to the best of us.'],
    labubu: ['Secret Pull', 'Summon a Labubu.'],
  },
  events: {
    bloodMoon: 'The Ohio Moon is rising... Only in Ohio.',
    sixSevenTime: "It's 6:07. You know what that means. 🤲",
    sahurWarning: 'Tung... tung... tung... You hear distant drumming. It is almost Sahur.',
    dawn: 'Good morning! Tralalero tralala!',
  },
  bossTaunts: {
    king_slime: ['SKIBIDI DOP DOP DOP YES YES!', 'Bow before your king (of slime)!', 'Brr brr skibidi dop!'],
    eye_of_cthulhu: ['*side-eye intensifies*', 'Bro really thought...', 'Chat, is this guy serious?', 'Ratio.'],
    tung_sahur: ['TUNG TUNG TUNG TUNG TUNG TUNG TUNG TUNG TUNG SAHUR!', 'SAHUR!!', 'Wake up. It is Sahur.', 'Tung. Tung. Tung.'],
    wall_of_flesh: ['YOU CANNOT ESCAPE THE BRAINROT', 'Skibidi Ohio Rizz Gyatt Fanum Tax Sigma', 'I AM THE FINAL SCROLL', '6... 7...', 'LOCK IN, MORTAL'],
  },
  sixSevenShouts: ['SIX SEVEN!', '6️⃣7️⃣!', 'SIX SEVEEEN!', '67!!', 'six... SEVEN!'],
  enemyChatter: {
    zombie: ['npc dialogue option 1...', 'braaains... rot...', 'fr fr...', 'is this ohio...', 'uuuh... gyatt...'],
    skibidi: ['skibidi dop dop yes yes', 'skibidi skibidi', 'brrr skibidi', 'dop dop dop'],
    fanum: ['fanum tax!', 'that looks bussin, ill take it', 'tax season baby'],
    tung: ['tung tung tung', 'sahur...'],
    tralalero: ['tralalero tralala!', 'porco dio porco allah'],
    bombardiro: ['BOMBARDIRO CROCODILO!', 'bombardiro!!'],
    ballerina: ['mi mi mi!', 'ballerina cappuccina!'],
  },
  chatReactions: ['chat is this real', 'W', 'L', 'ratio', 'no way', 'he is so him', 'aura +1000', 'cooked', 'bro is locked in', 'bussin', 'sheesh', 'glazing fr', 'that was sigma'],
};

function memePick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function fmtMeme(s, vars) { return s.replace(/\{(\w+)\}/g, (_, k) => vars[k] != null ? vars[k] : ''); }
